FROM redis:5.0.5-alpine


LABEL version="1.0.0"
LABEL author="dhtmdgkr123"
LABEL email="osh12201@gmail.com"

# COPY ./setThp.sh /
# RUN chmod +x /setThp.sh
# ENTRYPOINT ["/setThp.sh"]

# RUN /bin/bash -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
# RUN /bin/bash -c "echo never > /sys/kernel/mm/transparent_hugepage/defrag"